
[gcp_service_account]
type = "service_account"
project_id = "primal-oxide-478714-s0"
private_key_id = "6a016bdbbe5417838c9df5533280e112030080b0"

# ⚠️ Colle TOUTE la clé privée sur UNE seule ligne, en gardant les \n
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEv...........==\n-----END PRIVATE KEY-----\n"

client_email = "everinsight-coach@primal-oxide-478714-s0.iam.gserviceaccount.com"
client_id = "1179830406096813155589"
token_uri = "https://oauth2.googleapis.com/token"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/everinsight-coach%40primal-oxide-478714-s0.iam.gserviceaccount.com"

[google_sheets]
sheet_id = "1jVRvP6AQtnfKc_UWqIa2F0866O58iFf8SdHtMVwd0Jo"
[smtp]
host = "smtp.gmail.com"
port = 587
email = "nguyen.valery1@gmail.com"
password = "Bi@rritz64"
from_email = "nguyen.valery1@gmail.com"   
from_name  = "EVERINSIGHT, votre Coach pour développer vos softskills"          
